version: '3.8'

services:
  postgres:
    container_name: postgres_adonis_services
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - 5432:5432

volumes:
  postgres_volume: